spring:
  application:
    name: eureka-server  #eureka server注册的name，唯一标识

server:
  port: 1111  #eureka server服务的端口号

eureka:
  instance:
    hostname: localhost
  client:
    registerWithEureka: false  # Eureka服务注册中心也会将自己作为客户端来尝试注册它自己，需要禁用
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/